spring:
  rabbitmq:
    host:
      rabbitmq
    port:
      5672
  cloud:
    consul:
      discovery:
        enabled: true
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${spring.cloud.client.hostname}:${random.value}